version: "3"
services:
  proxy:
    image: cs124/jeed-proxy
    pull_policy: build
    build: proxy/.
    ports:
      - 8888:8888
    environment:
      - JEED_SERVER=http://jeed:8888
      - MONGODB=mongodb://mongodb:27017/jeed_demo
      - GOOGLE_CLIENT_IDS=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    depends_on:
      - jeed
      - mongodb
    volumes:
      - ./proxy/dist:/server/dist
  jeed:
    image: cs125/jeed:latest
    environment:
      - LIMITS_EXECUTION_TIMEOUT=1000
      - LIMITS_PLUGINS_LINECOUNTLIMIT=32768
      - LIMITS_EXECUTION_MAXEXTRATHREADS=8
  mongodb:
    image: mongo:4.4.8
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
