version: "3"
services:
  jeed:
    image: "cs125/jeed:latest"
    depends_on:
      - mongodb
    ports:
      - "8888:8888"
    environment:
      - "HOSTS=http://localhost:1234"
      - "SEMESTER=Demo"
      - "HTTP=http://0.0.0.0:8888"
      - "MONGODB=mongodb://mongodb/demo"
      - "AUTH_GOOGLE_CLIENTIDS=${GOOGLE_CLIENT_IDS}"
      - "LIMITS_EXECUTION_TIMEOUT=1000"
      - "LIMITS_EXECUTION_MAXEXTRATHREADS=8"
      - "DOCKER_HOST=dind:2375"
      - "JEED_CONTAINER_TMP_DIR=/tmp/"
    volumes:
      - "jeed_docker:/tmp/"
  element-tracker:
    image: "cs125/element-tracker:latest"
    depends_on:
      - mongodb
    ports:
      - "8889:8888"
    environment:
      - "MONGODB=mongodb://mongodb/demo"
      - "GOOGLE_CLIENT_IDS=${GOOGLE_CLIENT_IDS}"
  mace:
    image: "cs125/mace:latest"
    depends_on:
      - mongodb
    ports:
      - "8890:8888"
    environment:
      - "MONGODB=mongodb://mongodb/demo"
      - "GOOGLE_CLIENT_IDS=${GOOGLE_CLIENT_IDS}"
  mongodb:
    image: "bitnami/mongodb:4.2"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami"
  dind:
    image: "docker:19.03-dind"
    entrypoint: /bin/sh -c "rm -f /var/run/docker.pid && dockerd --host=tcp://0.0.0.0:2375"
    privileged: true
    volumes:
      - "dind_data:/var/lib/docker"
      - "jeed_docker:/tmp/"
volumes:
  jeed_docker:
  mongodb_data:
    driver: local
  dind_data:
    driver: local
