version: "3"
services:
  proxy:
    ports:
      - "8888:8888"
    image: "cs124/jeed-proxy:latest"
    environment:
      - "JEED_SERVER=http://jeed:8888"
      - "MONGODB=mongodb://mongodb:27017/jeed_demo"
    depends_on:
      - jeed
      - mongodb
  jeed:
    image: "cs125/jeed:latest"
    environment:
      - "LIMITS_EXECUTION_TIMEOUT=1000"
      - "LIMITS_EXECUTION_MAXEXTRATHREADS=8"
  mongodb:
    image: "bitnami/mongodb:4.4.3"
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    volumes:
      - "mongodb_data:/bitnami"
volumes:
  mongodb_data:
    driver: local
