version: "2"
networks:
  jeed:
    driver: bridge
services:
  mongodb:
    image: "bitnami/mongodb:4.2"
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    volumes:
      - "mongodb_data:/bitnami"
    networks:
      - jeed
volumes:
  mongodb_data:
    driver: local
