apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeed-demo-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jeed-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: jeed-demo
    spec:
      containers:
      - name: jeed-demo
        image: cs125/jeed:latest
        env:
        - name: HTTP
          value: http://0.0.0.0:80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jeed-demo-service
spec:
  selector:
    app: jeed-demo
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
  name: jeed-demo-ingress
spec:
  rules:
  - http:
      paths:
      - path: /demos/jeed
        backend:
          serviceName: jeed-demo-service
          servicePort: 80
