apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeed-deployment
  namespace: jeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeed
  template:
    metadata:
      labels:
        app: jeed
    spec:
      containers:
      - name: jeed
        image: cs125/jeed:2020.2.5
        ports:
        - containerPort: 8888
        env:
        - name: SEMESTER
          value: Spring2020
        - name: HTTP
          value: http://0.0.0.0:8888
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO
        - name: AUTH_GOOGLE_CLIENTID
          valueFrom:
            secretKeyRef:
              name: google-client-id
              key: GOOGLE_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: jeed-service
  namespace: jeed
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8888
  selector:
    app: jeed
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: jeed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-redirect-from: /
    nginx.ingress.kubernetes.io/proxy-redirect-to: /jeed/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: jeed-ingress
spec:
  rules:
  - http:
      paths:
      - path: /jeed(/|$)(.*)
        backend:
          serviceName: jeed-service
          servicePort: 80
